# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountAmount', models.FloatField()),
                ('accountUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseTime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('expenseType', models.CharField(choices=[('food', 'food'), ('education', 'education'), ('travel', 'travel'), ('shopping', 'shopping'), ('extra', 'extra'), ('living', 'living')], default='extra', max_length=20)),
                ('expenseItem', models.CharField(max_length=100)),
                ('expenseAmount', models.FloatField()),
                ('expenseUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionAmount', models.FloatField()),
                ('transactionStatus', models.BooleanField()),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionFrom', to=settings.AUTH_USER_MODEL)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFacebookId', models.CharField(max_length=100)),
                ('userGoogleId', models.CharField(max_length=100)),
                ('userPicUrl', models.URLField()),
                ('friends', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
